version: "3.7"
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Adc12345
      MYSQL_DATABASE: CybersoftProject
    ports:
      - "3307:3306"
    volumes:
      - ./database/ProjectDBCybersoftBC02.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - smartvoucher-network

  redis-container:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - smartvoucher-network

  smartvoucher-container:
    container_name: smartvoucher-container
    build:
      context: .
      dockerfile: DockerFileSpringboot
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8-container:3306/CybersoftProject?ServerTimezone=UTC&allowPublicKeyRetrieval=true
      MYSQL_ROOT_PASSWORD: Adc12345
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
    depends_on:
      - mysql8-container
    networks:
      - smartvoucher-network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8082/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  voucher-frontend-container:
    container_name: voucher-frontend-container
    build:
      context: .
      dockerfile: DockerFileVoucherFE
    ports:
      - "3000:80"
    restart: always
    networks:
      - smartvoucher-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/" ]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  smartvoucher-network:
      name: smartvoucher-network
      driver: bridge

#docker-compose -f ./deployment.yml up -d mysql8-container
#docker-compose -f ./deployment.yml up -d redis-container
#docker-compose -f ./deployment.yml up -d smartvoucher-container --build
#docker-compose -f ./deployment.yml up -d voucher-frontend-container --build


